-- DROP COURSE INDEXES

DROP INDEX IF EXISTS CoursesIDX ON Courses;
DROP INDEX IF EXISTS CoursesMeetingsIDX ON CoursesMeetings;
DROP INDEX IF EXISTS StationaryCourseIDX ON StationaryCourse;

-- DROP STUDIES INDEXES
DROP INDEX IF EXISTS StudiesIDX ON Studies;
DROP INDEX IF EXISTS StudentsIDX ON Students;
DROP INDEX IF EXISTS InternshipsIDX ON Internships;
DROP INDEX IF EXISTS StudySemestersIDX ON StudySemesters;
DROP INDEX IF EXISTS StationaryStudyIDX ON StationaryStudy;
DROP INDEX IF EXISTS StudiesMeetingsIDX ON StudiesMeetings;
DROP INDEX IF EXISTS StudyMeetupsIDX ON StudyMeetups;
DROP INDEX IF EXISTS FinalExamsIDX ON FinalExams;

-- DROP PEOPLE INDEXES
DROP INDEX IF EXISTS EmployeesIDX ON Employees;
DROP INDEX IF EXISTS TranslatorsIDX ON Translators;
DROP INDEX IF EXISTS UsersIDX ON Users;
